"""
Constants
"""

# Models
RECOMMEND_MODEL_USER = "User"
RECOMMEND_MODEL_BOARD = "Board"
RECOMMEND_MODEL_CARD = "Card"

# Attributes
RECOMMEND_MODEL_ATTR_ID = "uid"
RECOMMEND_MODEL_ATTR_EMAIL = "email_address"
RECOMMEND_MODEL_ATTR_BOARD_NAME = "name"
RECOMMEND_MODEL_ATTR_BOARD_OWNER_ID = "owner_uid"
