"""
Constants
"""

# Models
RECOMMEND_MODEL_USER = "User"
RECOMMEND_MODEL_BOARD = "Board"
RECOMMEND_MODEL_CARD = "Card"

# Attributes
RECOMMEND_MODEL_ATTR_ID = "uid"
RECOMMEND_MODEL_ATTR_EMAIL = "email_address"
RECOMMEND_MODEL_ATTR_BOARD_NAME = "name"
RECOMMEND_MODEL_ATTR_BOARD_OWNER_ID = "owner_uid"
RECOMMEND_MODEL_ATTR_CARD_URL = "url"
RECOMMEND_MODEL_ATTR_CARD_TITLE = "title"
RECOMMEND_MODEL_ATTR_CARD_DESCRIPTION = "description"
RECOMMEND_MODEL_ATTR_CARD_IMAGE = "image"
RECOMMEND_MODEL_ATTR_CARD_BOARD_ID = "board_uid"
